### ISSUE TITLE
config.plist-only fix

### ISSUE THREAD

**Issue by hameerabbasi** [osy86/USBWakeFixup#2]
I found a `config.plist` only fix via Clover's `AddProperties`.

```xml
        <key>Devices</key>
	<dict>
		<key>Properties</key>
		<dict>
			<key>PciRoot(0x0)/Pci(0x14,0x0)</key>
			<dict>
				<key>acpi-wake-type</key>
				<data>AQAAAA==</data>
			</dict>
		</dict>
	</dict>
```

Notice that the PCI-ID listed above is for Z370, for other chipsets it may differ. Use [`gfxutil`](https://github.com/acidanthera/gfxutil) to find yours:

```bash
./gfxutil -f XHC
# Probably unnecessary, but, for completeness
./gfxutil -f EHC1
./gfxutil -f EHC2
```

**Comment by ReddestDream** [comment]
I can't reproduce this working. I don't get a (User) wake when I do it. I have a Z270 board.

**Comment by osy86** [comment]
Yes, that works if you don’t suffer from the PM_Status corruption issue that I see in a lot of boards running intel PCH USB.

**Comment by hameerabbasi** [comment]
I’ll keep it here for reference.

**Comment by codecowboy** [comment]
Is AQAAAA== base 64 for null? I can't seem to find the equivalent to add via clover configurator and it doesn't let you add a blank entry

**Comment by hameerabbasi** [comment]
Base64 for `<01000000>`.
