### ISSUE TITLE
Multiple USB controllers

### ISSUE THREAD

**Issue by BbIKTOP** [osy86/USBWakeFixup#5]
Not sure it's an issue, maybe I just don't understand how to do it yet. I have a computer with multiple (2) XHC, I named them XHC and XHC2. But I cannot make USBWakeFixup to work with both. Is it possible?

**Comment by osy** [comment]
You need to make two devices `USBW` and `USBY` one point to `XHC` and the other to `XHC2`.

**Comment by BbIKTOP** [comment]
This is exactly what I tried to do:


`

 DefinitionBlock ("", "SSDT", 2, "OSY86 ", "USBW", 0x00001000)
 {
    External (\_SB.PCI0.XHC._PRW, MethodObj)
    External (\_SB.PCI0.XHC2._PRW, MethodObj)
    If (CondRefOf (\_OSI, Local0) && _OSI ("Darwin"))
    {
        Device (\_SB.USBW)
        {
            Name (_HID, "PNP0D10")  // _HID: Hardware ID
            Name (_UID, "WAKE")  // _UID: Unique ID

            Method (_PRW, 0, NotSerialized)  // _PRW: Power Resources for Wake
            {
                Return (\_SB.PCI0.XHC._PRW ()) // Replace with path to your USB device
            }
        }
    }
    If (CondRefOf (\_OSI, Local0) && _OSI ("Darwin"))
    {
        Device (\_SB.USBV)
        {
            Name (_HID, "PNP0D10")  // _HID: Hardware ID
            Name (_UID, "WAKE")  // _UID: Unique ID

            Method (_PRW, 0, NotSerialized)  // _PRW: Power Resources for Wake
            {
                Return (\_SB.PCI0.XHC2._PRW ()) // Replace with path to your USB device
            }
        }
    }
 }
`
Observe only first device having acpi-wake-gpe:
<img width="564" alt="image" src="https://user-images.githubusercontent.com/24525137/70395643-79e06b80-1a09-11ea-98e8-59a51fd7fef9.png">
<img width="557" alt="image" src="https://user-images.githubusercontent.com/24525137/70395645-85339700-1a09-11ea-9444-fbbced09b702.png">
Is it ok?
Thank you so much, it's great!

**Comment by osy** [comment]
Check the second one has a _PRW method

**Comment by BbIKTOP** [comment]
Unfortunately I have no idea how to do that properly. I extracted the table from the current acpi with maciasl and observe both devices have this method. I can add debug prints to it to see whether it called, but maybe this info is enough and everything works fine?

<img width="847" alt="image" src="https://user-images.githubusercontent.com/24525137/70396337-b368a500-1a10-11ea-9078-30c5cd0cfb57.png">

**Comment by BbIKTOP** [comment]
Just checked it once more without adding debug and ssdt recompilation - looks like it works fine. Mouse pluugged to this usb wakes computer almost immediately. I'll check with debug prints tomorrow, but I suppose this issue can be closed now, thank you so much!
